import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

import ToastifyProvider from "@/context/ToastContext";
import SettingsProvider from "@/context/SettingsContext";
import GlobalProvider from "@/context/GlobalContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <GlobalProvider>
          <SettingsProvider>
            <div className="flex-1 px-6 md:px-20 py-24">
              <ToastifyProvider  autoClose={30000} />
              {children}</div>
          </SettingsProvider>
        </GlobalProvider>
        <Footer />
      </body>
    </html>
  );
}
